project:
  type: website
  render: 
    - "*.qmd"
    - "!files/"
  output-dir: docs
  resources: 
    - "files/" 
    - "photos/"
    - "resources/"

website:
  title: "SpectralWeeaboo.github.io"
  site-url: www.JMT.info
  navbar:
    left:
    
      - href: https://github.com/SpectralWeeaboo/SpectralWeeaboo.github.io
        text: Home
      - about.qmd
      - Resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


editor: visual
