project:
  type: website
  render: 
    - "*.qmd"
    - "!files/"
  output-dir: docs
  resources: 
    - "files/" 
    - "photos/"
    - "resources/"
    - "cv/"
    - "p/"
website:
  title: "JMT"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



