project:
  type: website
  output-dir: docs

website:
  title: "JMT"
  sidebar: false
  search: false
  site-url: SpectralWeeaboo.github.io
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    page-layout: full
    theme: cosmo
    css: styles.css
    toc: true


editor: source