project:
  type: website
  render: 
    - "*.qmd"
    - "!files/"
  output-dir: docs


website:
  title: "Juan Manuel Torres"
  site-url: www.JuanMT.info
  navbar:
    left:
      - href: https://github.com/SpectralWeeaboo/SpectralWeeaboo.github.io
        text: Home
      - about.qmd
      - Resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


editor: visual
