project:
  type: website
  output-dir: docs

website:
  title: "JMT"
  sidebar: false
  search: false
  site-url: spectralweeaboo.github.io/JMTQuarto
  navbar:
    right:
    
      - href: index.qmd
        text: Home
        
      - href: about.qmd
        text: About
      
      - href: CV.qmd
        text: CV
        
      - href: projects.qmd
        text: Projects
      
      - icon: github
        href: https://github.com/SpectralWeeaboo/JMTQuarto
        
      - icon: linkedin
        href: https://www.linkedin.com/in/juan-torres-80a543297/
      

format:
  html:
    page-layout: full
    theme: darkly
    css: styles.css
    toc: false


editor: source